#ifdef DDYIELD_COUNT
#	if DDYIELD_COUNT == -1
#		define DDYIELD_COUNT 0
DDCORO_LABEL_0:
#	elif DDYIELD_COUNT == 0
#		define DDYIELD_COUNT 1
DDCORO_LABEL_1 :
#	elif DDYIELD_COUNT == 1
#		define DDYIELD_COUNT 2
DDCORO_LABEL_2 :
#	elif DDYIELD_COUNT == 2
#		define DDYIELD_COUNT 3
DDCORO_LABEL_3 :
#	elif DDYIELD_COUNT == 3
#		define DDYIELD_COUNT 4
DDCORO_LABEL_4 :
#	elif DDYIELD_COUNT == 4
#		define DDYIELD_COUNT 5
DDCORO_LABEL_5 :
#	elif DDYIELD_COUNT == 5
#		define DDYIELD_COUNT 6
DDCORO_LABEL_6 :
#	elif DDYIELD_COUNT == 6
#		define DDYIELD_COUNT 7
DDCORO_LABEL_7 :
#	elif DDYIELD_COUNT == 7
#		define DDYIELD_COUNT 8
DDCORO_LABEL_8 :
#	elif DDYIELD_COUNT == 8
#		define DDYIELD_COUNT 9
DDCORO_LABEL_9 :
#	elif DDYIELD_COUNT == 9
#		define DDYIELD_COUNT 10
DDCORO_LABEL_10 :
#	elif DDYIELD_COUNT == 10
#		define DDYIELD_COUNT 11
DDCORO_LABEL_11 :
#	elif DDYIELD_COUNT == 11
#		define DDYIELD_COUNT 12
DDCORO_LABEL_12 :
#	elif DDYIELD_COUNT == 12
#		define DDYIELD_COUNT 13
DDCORO_LABEL_13 :
#	elif DDYIELD_COUNT == 13
#		define DDYIELD_COUNT 14
DDCORO_LABEL_14 :
#	elif DDYIELD_COUNT == 14
#		define DDYIELD_COUNT 15
DDCORO_LABEL_15 :
#	elif DDYIELD_COUNT == 15
#		define DDYIELD_COUNT 16
DDCORO_LABEL_16 :
#	elif DDYIELD_COUNT == 16
#		define DDYIELD_COUNT 17
DDCORO_LABEL_17 :
#	elif DDYIELD_COUNT == 17
#		define DDYIELD_COUNT 18
DDCORO_LABEL_18 :
#	elif DDYIELD_COUNT == 18
#		define DDYIELD_COUNT 19
DDCORO_LABEL_19 :
#	elif DDYIELD_COUNT == 19
#		define DDYIELD_COUNT 20
DDCORO_LABEL_20 :
#	elif DDYIELD_COUNT == 20
#		define DDYIELD_COUNT 21
DDCORO_LABEL_21 :
#	elif DDYIELD_COUNT == 21
#		define DDYIELD_COUNT 22
DDCORO_LABEL_22 :
#	elif DDYIELD_COUNT == 22
#		define DDYIELD_COUNT 23
DDCORO_LABEL_23 :
#	elif DDYIELD_COUNT == 23
#		define DDYIELD_COUNT 24
DDCORO_LABEL_24 :
#	elif DDYIELD_COUNT == 24
#		define DDYIELD_COUNT 25
DDCORO_LABEL_25 :
#	elif DDYIELD_COUNT == 25
#		define DDYIELD_COUNT 26
DDCORO_LABEL_26 :
#	elif DDYIELD_COUNT == 26
#		define DDYIELD_COUNT 27
DDCORO_LABEL_27 :
#	elif DDYIELD_COUNT == 27
#		define DDYIELD_COUNT 28
DDCORO_LABEL_28 :
#	elif DDYIELD_COUNT == 28
#		define DDYIELD_COUNT 29
DDCORO_LABEL_29 :
#	elif DDYIELD_COUNT == 29
#		define DDYIELD_COUNT 30
DDCORO_LABEL_30 :
#	elif DDYIELD_COUNT == 30
#		define DDYIELD_COUNT 31
DDCORO_LABEL_31 :
#	elif DDYIELD_COUNT == 31
#		define DDYIELD_COUNT 32
DDCORO_LABEL_32 :
#	elif DDYIELD_COUNT == 32
#		define DDYIELD_COUNT 33
DDCORO_LABEL_33 :
#	elif DDYIELD_COUNT == 33
#		define DDYIELD_COUNT 34
DDCORO_LABEL_34 :
#	elif DDYIELD_COUNT == 34
#		define DDYIELD_COUNT 35
DDCORO_LABEL_35 :
#	elif DDYIELD_COUNT == 35
#		define DDYIELD_COUNT 36
DDCORO_LABEL_36 :
#	elif DDYIELD_COUNT == 36
#		define DDYIELD_COUNT 37
DDCORO_LABEL_37 :
#	elif DDYIELD_COUNT == 37
#		define DDYIELD_COUNT 38
DDCORO_LABEL_38 :
#	elif DDYIELD_COUNT == 38
#		define DDYIELD_COUNT 39
DDCORO_LABEL_39 :
#	elif DDYIELD_COUNT == 39
#		define DDYIELD_COUNT 40
DDCORO_LABEL_40 :
#	elif DDYIELD_COUNT == 40
#		define DDYIELD_COUNT 41
DDCORO_LABEL_41 :
#	elif DDYIELD_COUNT == 41
#		define DDYIELD_COUNT 42
DDCORO_LABEL_42 :
#	elif DDYIELD_COUNT == 42
#		define DDYIELD_COUNT 43
DDCORO_LABEL_43 :
#	elif DDYIELD_COUNT == 43
#		define DDYIELD_COUNT 44
DDCORO_LABEL_44 :
#	elif DDYIELD_COUNT == 44
#		define DDYIELD_COUNT 45
DDCORO_LABEL_45 :
#	elif DDYIELD_COUNT == 45
#		define DDYIELD_COUNT 46
DDCORO_LABEL_46 :
#	elif DDYIELD_COUNT == 46
#		define DDYIELD_COUNT 47
DDCORO_LABEL_47 :
#	elif DDYIELD_COUNT == 47
#		define DDYIELD_COUNT 48
DDCORO_LABEL_48 :
#	elif DDYIELD_COUNT == 48
#		define DDYIELD_COUNT 49
DDCORO_LABEL_49 :
#	elif DDYIELD_COUNT == 49
#		define DDYIELD_COUNT 50
DDCORO_LABEL_50 :
#	elif DDYIELD_COUNT == 50
#		define DDYIELD_COUNT 51
DDCORO_LABEL_51 :
#	elif DDYIELD_COUNT == 51
#		define DDYIELD_COUNT 52
DDCORO_LABEL_52 :
#	elif DDYIELD_COUNT == 52
#		define DDYIELD_COUNT 53
DDCORO_LABEL_53 :
#	elif DDYIELD_COUNT == 53
#		define DDYIELD_COUNT 54
DDCORO_LABEL_54 :
#	elif DDYIELD_COUNT == 54
#		define DDYIELD_COUNT 55
DDCORO_LABEL_55 :
#	elif DDYIELD_COUNT == 55
#		define DDYIELD_COUNT 56
DDCORO_LABEL_56 :
#	elif DDYIELD_COUNT == 56
#		define DDYIELD_COUNT 57
DDCORO_LABEL_57 :
#	elif DDYIELD_COUNT == 57
#		define DDYIELD_COUNT 58
DDCORO_LABEL_58 :
#	elif DDYIELD_COUNT == 58
#		define DDYIELD_COUNT 59
DDCORO_LABEL_59 :
#	elif DDYIELD_COUNT == 59
#		define DDYIELD_COUNT 60
DDCORO_LABEL_60 :
#	elif DDYIELD_COUNT == 60
#		define DDYIELD_COUNT 61
DDCORO_LABEL_61 :
#	elif DDYIELD_COUNT == 61
#		define DDYIELD_COUNT 62
DDCORO_LABEL_62 :
#	elif DDYIELD_COUNT == 62
#		define DDYIELD_COUNT 63
DDCORO_LABEL_63 :
#	endif
#else
#error No Include DDCORO_BEGIN()
#endif
